//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esri.ArcGISRuntime.ExampleApps.DataCollection.Shared.LocalizedStrings.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Esri.ArcGISRuntime.ExampleApps.DataCollection.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add attchment.
        /// </summary>
        internal static string AddAttachment_Tooltip {
            get {
                return ResourceManager.GetString("AddAttachment_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Feature.
        /// </summary>
        internal static string AddFeature_Tooltip {
            get {
                return ResourceManager.GetString("AddFeature_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the location where you would like to add a feature.
        /// </summary>
        internal static string AddFeatureLabel_Line1_Text {
            get {
                return ResourceManager.GetString("AddFeatureLabel_Line1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan and zoom map under pin.
        /// </summary>
        internal static string AddFeatureLabel_Line2_Text {
            get {
                return ResourceManager.GetString("AddFeatureLabel_Line2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Related Record.
        /// </summary>
        internal static string AddRelatedRecord_Tooltip {
            get {
                return ResourceManager.GetString("AddRelatedRecord_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication error.
        /// </summary>
        internal static string AuthError_Title {
            get {
                return ResourceManager.GetString("AuthError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButton_Content {
            get {
                return ResourceManager.GetString("CancelButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Edits.
        /// </summary>
        internal static string CancelEdits_Tooltip {
            get {
                return ResourceManager.GetString("CancelEdits_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseButton_Tooltip {
            get {
                return ResourceManager.GetString("CloseButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update Condition &amp; DBH.
        /// </summary>
        internal static string ConditionDBH_UpdateError_Title {
            get {
                return ResourceManager.GetString("ConditionDBH_UpdateError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete attachment.
        /// </summary>
        internal static string DeleteAttachment_Tooltip {
            get {
                return ResourceManager.GetString("DeleteAttachment_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteButton_Content {
            get {
                return ResourceManager.GetString("DeleteButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will remove the feature from the database permanently and cannot be undone..
        /// </summary>
        internal static string DeleteConfirmation_Message {
            get {
                return ResourceManager.GetString("DeleteConfirmation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this feature?.
        /// </summary>
        internal static string DeleteConfirmation_Title {
            get {
                return ResourceManager.GetString("DeleteConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will remove the attachment from the database permanently and cannot be undone..
        /// </summary>
        internal static string DeleteConfirmationAttachment_Message {
            get {
                return ResourceManager.GetString("DeleteConfirmationAttachment_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this attachment?.
        /// </summary>
        internal static string DeleteConfirmationAttachment_Title {
            get {
                return ResourceManager.GetString("DeleteConfirmationAttachment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will no longer have a map if you are in offline mode. .
        /// </summary>
        internal static string DeleteMap_Message {
            get {
                return ResourceManager.GetString("DeleteMap_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the offline map?.
        /// </summary>
        internal static string DeleteMap_Title {
            get {
                return ResourceManager.GetString("DeleteMap_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Offline Map.
        /// </summary>
        internal static string DeleteMapButton_Label {
            get {
                return ResourceManager.GetString("DeleteMapButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The offline map contains un-synchronized changes. You will no longer have a map when you are in offline mode and will lose your existing changes. .
        /// </summary>
        internal static string DeleteMapWithUnsyncedChanges_Message {
            get {
                return ResourceManager.GetString("DeleteMapWithUnsyncedChanges_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Record.
        /// </summary>
        internal static string DeleteRecord_Tooltip {
            get {
                return ResourceManager.GetString("DeleteRecord_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving application settings.
        /// </summary>
        internal static string DeserializationError_Title {
            get {
                return ResourceManager.GetString("DeserializationError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device is offline.
        /// </summary>
        internal static string DeviceOffline_Title {
            get {
                return ResourceManager.GetString("DeviceOffline_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        internal static string DiscardButton_Content {
            get {
                return ResourceManager.GetString("DiscardButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will quit your edit sessions and will cause all of your unsaved changes to be lost..
        /// </summary>
        internal static string DiscardEditsConfirmation_Message {
            get {
                return ResourceManager.GetString("DiscardEditsConfirmation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to discard changes?.
        /// </summary>
        internal static string DiscardEditsConfirmation_Title {
            get {
                return ResourceManager.GetString("DiscardEditsConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string DownloadButton_Content {
            get {
                return ResourceManager.GetString("DownloadButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed.
        /// </summary>
        internal static string DownloadFailed_Title {
            get {
                return ResourceManager.GetString("DownloadFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing map for offline use. Please wait..
        /// </summary>
        internal static string DownloadingMessage_Text {
            get {
                return ResourceManager.GetString("DownloadingMessage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the region of the map to take offline.
        /// </summary>
        internal static string DownloadLabel_Line1_Text {
            get {
                return ResourceManager.GetString("DownloadLabel_Line1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan and zoom map within rectangle.
        /// </summary>
        internal static string DownloadLabel_Line2_Text {
            get {
                return ResourceManager.GetString("DownloadLabel_Line2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download completed with errors.
        /// </summary>
        internal static string DownloadWithErrors_Title {
            get {
                return ResourceManager.GetString("DownloadWithErrors_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Record.
        /// </summary>
        internal static string EditRecord_Tooltip {
            get {
                return ResourceManager.GetString("EditRecord_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attachment file you are trying to open could not be located. Please try restarting the application..
        /// </summary>
        internal static string FileNotFound_Message {
            get {
                return ResourceManager.GetString("FileNotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string FileNotFound_Title {
            get {
                return ResourceManager.GetString("FileNotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string GenericAffirmativeButton_Content {
            get {
                return ResourceManager.GetString("GenericAffirmativeButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured.
        /// </summary>
        internal static string GenericError_Title {
            get {
                return ResourceManager.GetString("GenericError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string GenericNegativeButton_Content {
            get {
                return ResourceManager.GetString("GenericNegativeButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when attempting to retrieve relationships for the feature..
        /// </summary>
        internal static string GetFeatureRelationshipError_Message {
            get {
                return ResourceManager.GetString("GetFeatureRelationshipError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while identifying feature.
        /// </summary>
        internal static string IdentifyError_Title {
            get {
                return ResourceManager.GetString("IdentifyError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes to this record are invalid. Please correct and retry saving..
        /// </summary>
        internal static string InvalidInput_Message {
            get {
                return ResourceManager.GetString("InvalidInput_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input detected.
        /// </summary>
        internal static string InvalidInput_Title {
            get {
                return ResourceManager.GetString("InvalidInput_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application was unable to delete the offline map and needs to restart. .
        /// </summary>
        internal static string IOException_Message {
            get {
                return ResourceManager.GetString("IOException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO exception.
        /// </summary>
        internal static string IOException_Title {
            get {
                return ResourceManager.GetString("IOException_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string LogInButton_Label {
            get {
                return ResourceManager.GetString("LogInButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login unsuccessful.
        /// </summary>
        internal static string LoginUnsuccessful_Title {
            get {
                return ResourceManager.GetString("LoginUnsuccessful_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string LogOutButton_Label {
            get {
                return ResourceManager.GetString("LogOutButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map failed to load.
        /// </summary>
        internal static string MapLoadingError_Title {
            get {
                return ResourceManager.GetString("MapLoadingError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Tools.
        /// </summary>
        internal static string MoreTools_Tooltip {
            get {
                return ResourceManager.GetString("MoreTools_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device must be connected to a network to delete the offline map..
        /// </summary>
        internal static string NoDelete_DeviceOffline_Message {
            get {
                return ResourceManager.GetString("NoDelete_DeviceOffline_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device must be connected to a network to login..
        /// </summary>
        internal static string NoLogin_DeviceOffline_Message {
            get {
                return ResourceManager.GetString("NoLogin_DeviceOffline_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device is not connected to a network and you do not have an offline map downloaded. Please connect to a network to load map. .
        /// </summary>
        internal static string NoMap_DeviceOffline_Message {
            get {
                return ResourceManager.GetString("NoMap_DeviceOffline_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device must be connected to a network to work online..
        /// </summary>
        internal static string NoOnlineMode_DeviceOffline_Message {
            get {
                return ResourceManager.GetString("NoOnlineMode_DeviceOffline_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device must be connected to a network to synchronize the offline map..
        /// </summary>
        internal static string NoSync_DeviceOffline_Message {
            get {
                return ResourceManager.GetString("NoSync_DeviceOffline_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open attachment.
        /// </summary>
        internal static string OpenAttachment_Tooltip {
            get {
                return ResourceManager.GetString("OpenAttachment_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was canceled..
        /// </summary>
        internal static string OperationCancelled {
            get {
                return ResourceManager.GetString("OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when attempting to retrieve related records for the feature..
        /// </summary>
        internal static string QueryRelatedFeaturesError_Message {
            get {
                return ResourceManager.GetString("QueryRelatedFeaturesError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButton_Content {
            get {
                return ResourceManager.GetString("SaveButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Edits.
        /// </summary>
        internal static string SaveEdits_Tooltip {
            get {
                return ResourceManager.GetString("SaveEdits_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving application settings.
        /// </summary>
        internal static string SerializationError_Title {
            get {
                return ResourceManager.GetString("SerializationError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Detail.
        /// </summary>
        internal static string ShowDetailButton_Tooltip {
            get {
                return ResourceManager.GetString("ShowDetailButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize Offline Map.
        /// </summary>
        internal static string SyncButton_Label {
            get {
                return ResourceManager.GetString("SyncButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing map. Please wait..
        /// </summary>
        internal static string SynchingMessage_Text {
            get {
                return ResourceManager.GetString("SynchingMessage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Offline.
        /// </summary>
        internal static string WorkingOfflineButton_Label {
            get {
                return ResourceManager.GetString("WorkingOfflineButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Online.
        /// </summary>
        internal static string WorkingOnlineButton_Label {
            get {
                return ResourceManager.GetString("WorkingOnlineButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Offline.
        /// </summary>
        internal static string WorkOfflineButton_Label {
            get {
                return ResourceManager.GetString("WorkOfflineButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Online.
        /// </summary>
        internal static string WorkOnlineButton_Label {
            get {
                return ResourceManager.GetString("WorkOnlineButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to current location.
        /// </summary>
        internal static string ZoomButton_Tooltip {
            get {
                return ResourceManager.GetString("ZoomButton_Tooltip", resourceCulture);
            }
        }
    }
}
